# fly.toml app configuration file generated for xavier-ai-backend-v2 on 2025-06-11T01:10:53+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'xavier-ai-backend-v2'
primary_region = 'fra'

[build]

[env]
  FLASK_ENV = "production"
  ENVIRONMENT = "production"
  PYTHONPATH = "/app"
  PYTHONUNBUFFERED = "1"
  # Memory optimization
  MALLOC_TRIM_THRESHOLD = "100000"
  MALLOC_MMAP_THRESHOLD = "131072"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
