version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - app_network

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER:-xavier}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-xavierpassword}
      POSTGRES_DB: ${DB_NAME:-xavier_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app_network

  # Uncomment to enable backend service when ready
  # backend:
  #   build: ./back
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - FLASK_ENV=development
  #     - DATABASE_URL=postgresql://${DB_USER:-xavier}:${DB_PASSWORD:-xavierpassword}@postgres:5432/${DB_NAME:-xavier_db}
  #     - REDIS_URL=redis://redis:6379/0
  #   volumes:
  #     - ./back:/app
  #   depends_on:
  #     - redis
  #     - postgres
  #   networks:
  #     - app_network

volumes:
  redis_data:
  postgres_data:

networks:
  app_network:
    driver: bridge 